[package]
name = "distillate"
version = "0.0.0"
edition = "2018"

[dependencies]
chrono = "0.4"
handlebars = "4.1"
pulldown-cmark = { version = "0.8", features = ["simd"] }
serde_json = "1.0"
structopt = "0.3"
toml = "0.5"
